### ISSUE TITLE
CCMenu support

### ISSUE THREAD

**Issue by kaiwren** [srushti/goldberg#11]

**Comment by achamian** [comment]
Following routes are supported currently:

'XmlStatusReport.aspx', 'cctray.xml', 'cc.xml'

**Comment by achamian** [comment]
CCMenu : http://goldberg.c42.in/XmlStatusReport.aspx

We still need to differentiate between couple of statuses like 'sleeping'
and 'building' I guess. But otherwise it is working.

Regards,
Niranjan Paranjape.
