### ISSUE TITLE
Add robots.txt

### ISSUE THREAD

**Issue by jasim** [srushti/goldberg#114]
Search engine spiders are consuming an enormous amount of bandwidth trying to spider every build status. Only the home page and builds list (if required) should be allowed for crawling.

**Comment by pahnin** [comment]
Hi, I fixed this, I suppose.
Here's is my commit message https://github.com/pahnin/goldberg/commit/7bc8414cd201032c3ba283c7ea9d2e951797e98b
and link to repo https://github.com/pahnin/goldberg

Regards
