### ISSUE TITLE
Better error message for incorrect number of arguments

### ISSUE THREAD

**Issue by professor** [srushti/goldberg#116]
The directions very clearly say that the way to add a new project is the following:
   RAILS_ENV=production bin/goldberg add <url> <name> [--branch <branch_name>] [--scm <git|svn>]

In my haste, I mistook <name> as on optional. Here is what goldberg says  

RAILS_ENV=production bin/goldberg add git://github.com/professor/cmusv.git
There was problem adding the project.

In my opinion, I think there should be an error about missing the <name> field.

RAILS_ENV=production bin/goldberg add git://github.com/professor/cmusv.git CMUSV
Executing /usr/bin/env bash -c "git clone --depth 1 git://github.com/professor/cmusv.git /Users/tsedano/.goldberg/projects/CMUSV/code --branch master"

**Comment by srushti** [comment]
We now prompt the user for the missing arguments. 1eed860f2f017b93504e0849f5ddfe0d4517d9d7
