### ISSUE TITLE
view error when there are no rows in the builds table.

### ISSUE THREAD

**Issue by professor** [srushti/goldberg#117]
If you install goldberg, add a project, and start up the rails server (without running the poller) you will see this error. Namely, there are rows in the projects table, not no rows in the builds table. (You might wonder why this would ever happen, but I'll do that as a separate issue.)

ActionView::Template::Error (undefined method `revision' for nil:NilClass):
    16:       %span.github-url
    17:         = link_to "on Github", project.github_url
    18:     - if !project.culprits_for_failure.empty?
    19:       %span.culprit
    20:         = "(Possible culprit(s): #{project.culprits_for_failure})"
  app/models/project.rb:103:in`collect'
  app/models/project.rb:103:in `culprits_for_failure'
  app/views/home/_projects.html.haml:19:in`block in _app_views_home__projects_html_haml___2801943936578340937_70152287429120__1170576346776675652'
  app/views/home/_projects.html.haml:1:in `each'
  app/views/home/_projects.html.haml:1:in`_app_views_home__projects_html_haml___2801943936578340937_70152287429120__1170576346776675652'
  app/views/home/_group_projects.html.haml:3:in `_app_views_home__group_projects_html_haml___2467876166340770091_70152287740840_4119433557577715791'
  app/views/home/index.html.haml:13:in`_app_views_home_index_html_haml___393827389654930005_70152288139680__3344093698743789194'

**Comment by srushti** [comment]
This has been fixed now. Closing it accordingly. Let me know if it's still reproducible.
