### ISSUE TITLE
What's the best way to stop the poller?

### ISSUE THREAD

**Issue by professor** [srushti/goldberg#119]
On several occasions, if I stop the poller from the command line with control-c, it will leave the database in a state that will cause the rails server to be unable to render the page. 

Here's one of them

ActionView::Template::Error (undefined method `gsub' for nil:NilClass):
    1: - projects.each do |project|
    2:   - status = project_status(project)
    3:   .project-row{:class => status}
    4:     %form.force_build{:method => 'post', :action => project_force_path(project.name)}
    5:       %input{:type => 'submit', :value => "force build#{build_queued?(project) ? ' (build queued)' : ''}"}
  app/helpers/application_helper.rb:11:in`status'
  app/helpers/application_helper.rb:3:in `project_status'
  app/views/home/_projects.html.haml:2:in`block in _app_views_home__projects_html_haml__3419687771464421125_70302258007320__2992023346050178007'

**Comment by srushti** [comment]
Merging this with #102. We need to allow for the clean stopping (& starting) of the poller from the web app, which will be taken care of by #102. That should automatically sort this issue out. Closing this now.
