### ISSUE TITLE
config.after_build raises 'undefined method'

### ISSUE THREAD

**Issue by tmornini** [srushti/goldberg#126]
When I put this in a per-project configuration file:

```
config.after_build lambda { |build, project| `echo "project: #{project}, build: #{build}"` }
```

I get this from the poller:

```
Build on project boocx-core failed because of undefined method `after_build' for #<Project::Configuration::0x00000013b9b500>
```

Let me know if I can help out!

**Comment by aakashd** [comment]
Hello Tom,

We had replaced the after_build callback with on_build_completion, but forgot to change the documentation. Apologies for the inconvenience and thanks for bringing it to our attention.

Thanks,
Aakash

**Comment by srushti** [comment]
I'm closing this issue, and thanks again for reporting this.
