### ISSUE TITLE
git submodule support is not recursive

### ISSUE THREAD

**Issue by skizz** [srushti/goldberg#127]
It is common for projects in the iOS world to have recursive submodules. For a prominent example of this see ShareKit.

So it is not enough to do  "git pull && git submodule init && git submodule update".

We should actually do something like:
- git submodule init && git submodule update
- for each submodule : 
  - git submodule init && git submodule update

recursively.

**Comment by srushti** [comment]
Any ideas on Git commands we could use to do this? Basically, what do you run on your dev machines to get all submodules up-to-date?

**Comment by skizz** [comment]
Here's what I do:

``` ruby
task :checkout_submodules_hack do
  FileUtils.cd('Cali/Frameworks/ShareKit') do
    puts `pwd`
    `git submodule init && git submodule update`
  end
end 
```

There's no single command in git that will do this. You need to parse the git log and run it recursively in every directory.

**Comment by srushti** [comment]
@skizz Could you confirm the fix in 7b0bc34 works? It worked like this for me https://gist.github.com/2021967.

**Comment by skizz** [comment]
I'll try and check today

Thanks

Chris Stevenson - http://955dreams.com
Twitter: @chris_stevenson

**Comment by srushti** [comment]
I'm going to assume it's working. Please reopen this issue if the problem still exists.
