### ISSUE TITLE
Raise visible errors when Git pull fails

### ISSUE THREAD

**Issue by jasim** [srushti/goldberg#128]
Goldberg does not run any build if Git pull fails. There is no notification so it is hard to figure out what went wrong.

A typical case where this happens is:  
schema.rb is checked in. A new commit is made which has a migration; but this commit does not check in the updated schema.rb. Goldberg will at this point run the migration which will create a locally modified version (in the CI server) of the schema.rb. Next time Goldberg tries to pull - the conflict in schema.rb will cause it to fail.

**Comment by srushti** [comment]
The git pull issue specifically has been fixed since we do a hard reset before pulling now. But, this probably should still be done to account for scenarios where the version control server is not reachable (or other similar error).
