### ISSUE TITLE
Perform a git-reset before doing a git pull

### ISSUE THREAD

**Issue by skizz** [srushti/goldberg#129]
In many cases builds modify checked in code (e.g. to configure version numbers) or add files that are not checked in. In this case git will refuse to pull the latest code. 

Here's what happens for us (caused by version number updates):

```
Updating bd57572..8e66512
error: Your local changes to the following files would be overwritten by merge:
    Cali/Cali-Info.plist
    CaliApplicationTests/CaliApplicationTests-Info.plist
    CaliUnitTests/CaliUnitTests-Info.plist
    GTEngineTests/GTEngineTests-Info.plist
Please, commit your changes or stash them before you can merge.
Aborting
```

To address this problem it is important that Goldberg does a `git reset --hard` before trying to do a git pull.

**Comment by ghost** [comment]
Looks like this issue is resolved with above commit. Can you close it? :)
