### ISSUE TITLE
Fix home page refresh

### ISSUE THREAD

**Issue by srushti** [srushti/goldberg#135]
Currently, the web app refreshes the build statuses by reloading the entire page {c42/goldberg@913c4161424121b4b377e676ebdda216eb973020}. The original switch was meant to be a band-aid until we fixed the issue with the partial. I'd like to switch back and just load just the partial again.

**Comment by pahnin** [comment]
homepage refresh seems to be working just by uncommenting lines 5-13 in https://github.com/c42/goldberg/blob/master/app/views/home/index.html.haml and commenting lines 9-17 in https://github.com/c42/goldberg/blob/master/app/views/layouts/application.html.haml is there any other problem?

**Comment by pahnin** [comment]
I think lines 9-17  in https://github.com/c42/goldberg/blob/master/app/views/layouts/application.html.haml makes the builds view to reload every 5 seconds too we need that too?

**Comment by srushti** [comment]
No, we don't need it. The page reload was added as a stopgap.

**Comment by pahnin** [comment]
I've fixed it and added a little notifier message, i mean a small message will appear while processing the get request, i cudnt decide where to put this? below the projects list? or above it? once it is done I'll push and will make pull request. any suggestion where to put it?

**Comment by srushti** [comment]
I'm not sure we need a loading indicator. Instead I'd rather have a notification if the retrieval failed to let the user know the information they have is stale.

**Comment by pahnin** [comment]
ok working on that
