### ISSUE TITLE
Show status as success even build has been failed

### ISSUE THREAD

**Issue by sivagollapalli** [srushti/goldberg#152]
I have added rspec request specs with selenium integrated with it. Due to, it didn't attain stable connection with firefox  all specs has been failed. But it shows status as green which means build has been successfully. I don't know why? Could you please look into this?

**Comment by srushti** [comment]
It will depend entirely on the exit status of the build process. I'm guessing your build script (rake or whatever else you're using) isn't reporting the error properly.

Let me know if the exit code is returning properly and yet the build shows green.

**Comment by srushti** [comment]
I'm closing this issue for now.

Please let me know if you were able to resolve this issue.
