### ISSUE TITLE
Updated configuration page with jruby configuration

### ISSUE THREAD

**Issue by sivagollapalli** [srushti/goldberg#153]
I have gone through configuration page how to configure multiple ruby versions for various projects. But  I couldn't find any config regarding applications which uses jruby? 

Could you please let me know where I can find the configuration?

**Comment by srushti** [comment]
Like setting any other Ruby just put this line in your goldberg_config.rb

``` ruby
config.ruby = 'jruby'
```

Or replace the jruby in the above line with whatever you would use in your 'rvm use' in your build server. e.g. 'jruby-1.6.0'.

**Comment by srushti** [comment]
I'm closing this now. Reopen it if there's any problem.

**Comment by sivagollapalli** [comment]
Could you please update this on configuration documentation. So others will get to know this.

**Comment by srushti** [comment]
It is mentioned there. You can basically fill in any Ruby your RVM knows about.
