### ISSUE TITLE
Run ajax functionality specs using goldberg

### ISSUE THREAD

**Issue by sivagollapalli** [srushti/goldberg#154]
I am testing ajax functionality using rspec by provided ':js => true' option to describe block. It opens firefox browser and run the specifications. On local it's working fine but on goldberg server it fails as couldn't open the browser and run the specifications.  

How to make these specifications to pass?

**Comment by srushti** [comment]
It's hard to figure out why that might be, but off the top of my head I'd guess firefox hasn't been setup to open in headless mode.

**Comment by sivagollapalli** [comment]
It works for me. Thanks!!
