### ISSUE TITLE
Metadata/layout for the list of builds

### ISSUE THREAD

**Issue by kaiwren** [srushti/goldberg#16]
See http://goldberg.c42.in/projects/wrest
- Move the list to the left column so I don't have to scroll to the bottom of a long build log
- Colour successes and failures differently - not necessarily the entire line but some part of it
- Link the SHA of the build to the repository browser if one exists - especially useful for Github projects

**Comment by srushti** [comment]
I'm closing this since we've implemented the first two points, and I've created #56 for the third. I assume that's okay.
