### ISSUE TITLE
Allow invoking of a different target

### ISSUE THREAD

**Issue by srushti** [srushti/goldberg#31]
Currently, you can only run the default rake target, but you should be able to run a different target, e.g. something else which runs both "db:migrate" & "spec".

**Comment by aakashd** [comment]
If I change the custom command in DB to "db:migrate && rake" on goldberg, it works perfectly fine. We just need to change the project addition command interface to accept commands with space in it. Using commander might help us with it.

**Comment by srushti** [comment]
We can now specify a rake_task in goldberg_config.rb.
