### ISSUE TITLE
zsh:1: command not found: bundle

### ISSUE THREAD

**Issue by professor** [srushti/goldberg#32]
I'm looking at my build_log file and here is what I see....

__rvm_reset:14: no matches found: /Users/tsedano/.rvm/bin/default_*
__rvm_reset:14: no matches found: /Users/tsedano/.rvm/bin/passenger_*
__rvm_reset:14: no matches found: /Users/tsedano/.rvm/bin/editor_*
zsh:1: command not found: bundle
zsh:1: command not found: bundle

a) my ~/.rvm/bin directory contains my languages (I don't see passenger, etc in there)
ruby-1.9.2-p180
ruby-1.9.2-p180@goldberg
ruby-1.8.7-p302@rails3
...

b) I'm not sure why zsh is failing to find bundler. Maybe we need to setup zsh to understand about rvm and which ruby to use? Normally I default my entire system to 1.8.7 and I have specific projects use 1.9.2 -- today, I turned off my default rvm and zsh couldn't find bundler.

Any thoughts?

**Comment by professor** [comment]
I tried copying the goldberg/.rvmrc into ~/.goldberg which helped a little. Here's now my error:

__rvm_reset:14: no matches found: /Users/tsedano/.rvm/bin/default_*
__rvm_reset:14: no matches found: /Users/tsedano/.rvm/bin/passenger_*
__rvm_reset:14: no matches found: /Users/tsedano/.rvm/bin/editor_*
[31mCould not find activesupport-2.3.4 in any of the sources[0m
[31mCould not find activesupport-2.3.4 in any of the sources[0m

Where is the project getting built? -- never mind, just found it under ~/.goldberg/projects/NAME/code

**Comment by aakashd** [comment]
As you can see in the Goldberg source code, it already contains an rvmrc. The first error you had posted tells that you don't have bundler gem installed in the gemset (assuming you are using one) being used for your project.

1) Does your project have an rvmrc included?
2) Does your project use bundler?

**Comment by professor** [comment]
On Sun, Apr 10, 2011 at 10:16 AM, aakashd <reply+i-748628-4228c61358b79b2a9607d145fc9cab17f0bc6128@reply.github.com> wrote:
As you can see in the Goldberg source code, it already contains an rvmrc. The first error you had posted tells that you don't have bundler gem installed in the gemset (assuming you are using one) being used for your project.

1) Does your project have an rvmrc included?

It does not, but I'll create one.

2) Does your project use bundler?

Yes, here is my Gemfile.

source 'http://rubygems.org'

gem 'rails',    '2.3.4'
gem 'aws-s3'
gem 'mechanize', '1.0.0'
gem 'ruby-openid'
gem 'ruby-openid-apps-discovery'
gem 'rack-openid'

gem 'bundler'
gem 'delayed_job', '2.1.0.pre'

gem 'oauth'

gem 'heroku'
gem 'taps'

group :plugins do
  gem 'authlogic'
  gem 'calendar_date_select' 
end

group :production do
  gem 'rcov' #This should not be necessary, but it's used by the Rakefile and it needs to be removed
  gem 'factory_girl' #This is necessary when we want to load factory seeds into a production database
  gem 'vestal_versions', '1.0.2' #, :git => 'git://github.com/laserlemon/vestal_versions'
end

group :development, :test do
  gem 'rake'
  gem 'pg'
  gem 'mongrel'
  gem 'ruby-debug-base' #'0.10.3'
  gem 'ruby-debug-ide' #'0.4.6'
  gem 'shoulda'
  gem 'rcov'
  gem 'rdoc',    '2.4.3' #rdoc_rails required RDoc of 2.4.3 - http://stackoverflow.com/questions/2993435/rake-uninitialized-constant-rdocrdoc
  gem 'rspec-rails', '1.3.3'
  gem 'mocha'
  gem 'rspec',   '1.3.1'
  gem 'factory_girl'
  gem 'capybara'

  gem 'test-unit', '1.2.3' #Downgrading so that autotest, rspec will work

  gem 'vestal_versions', '1.0.2' #, :git => 'git://github.com/laserlemon/vestal_versions'
end

**Comment by professor** [comment]
I added a .rvmrc file into my repository. I expected and received the following warning. I was able to resolve this by doing a "cd ~/.goldberg/projects/PROJECTNAME/code" -- I'm wondering if this is something everyone will need to do and if so if it should be part of the README.

# 

  RVM has encountered a not yet trusted .rvmrc file in the
  current working directory which contains the following code:
  ============================================================

rvm ruby-1.8.7@rails2

  ============================================================
  Trusting an .rvmrc file means that whenever you cd into the
  directory RVM will excecute this .rvmrc script in your shell

  Do you wish to trust this .rvmrc from now on?
  ============================================================
  (y for yes, n for no) >

**Comment by aakashd** [comment]
Yes, as of now you need to cd into the directory and accept the rvmrc. We are working on doing this programmatically and should have it ready in next few days.

Did this solve your issue though?

**Comment by professor** [comment]
Yes this did. I'll close out this issue. I'll do a pull request for the documentation update.
