### ISSUE TITLE
goldberg should do a bundle install for each project

### ISSUE THREAD

**Issue by professor** [srushti/goldberg#34]
I would expect that goldberg would do a "bundle install" after pulling the latest from git.

__rvm_reset:14: no matches found: /Users/tsedano/.rvm/bin/default_*
__rvm_reset:14: no matches found: /Users/tsedano/.rvm/bin/passenger_*
__rvm_reset:14: no matches found: /Users/tsedano/.rvm/bin/editor_*
[31mCould not find activesupport-2.3.4 in any of the sources[0m
[31mCould not find activesupport-2.3.4 in any of the sources[0m

If I do a manual build install in the ~..goldberg/projects/PROJECT/code this goes away.

**Comment by aakashd** [comment]
Goldberg does execute <code>bundle check || bundle install</code> on projects where it finds Gemfile in source code. This might be some other issue as bundler is being takes care of by default.

To help us resolve it, could you please remove the project using <code>./bin/goldberg remove PROJECT_NAME</code>; and post build_log of the first build after adding the project?

**Comment by professor** [comment]
I decided to add the same git url as a second project. Here was my experience.

Build 1 - RVM has encountered a not yet trusted .rvmrc file, so I did a "rvm ruby-1.8.7@rails2"
Build 2 - it worked

I realized the reason it worked was this wasn't a new rvm gemset. If goldberg is running on your development machine, this is fine. I'm wanting to run goldberg on a stand alone server so that my students don't need to install goldberg. Here's how I was able to reproduce the problem.

Step 1) Alter my .rvmrc to a new gemset
rvm ruby-1.8.7@rails2tmp

Build 3 - Gemset 'rails2tmp' does not exist, rvm gemset create 'rails2tmp' first and zsh:1: command not found: bundle
So I did a "rvm gemset create 'rails2tmp'" and a "gem install bundler" and a "gem install rake"

Build 6 - [31mCould not find activesupport-2.3.4 in any of the sources[0m
Which means that goldberg did not run bundle install

The following are the build files
1/buildlog
__rvm_reset:14: no matches found: /Users/tsedano/.rvm/bin/default_*
__rvm_reset:14: no matches found: /Users/tsedano/.rvm/bin/passenger_*
__rvm_reset:14: no matches found: /Users/tsedano/.rvm/bin/editor_*

  ============================================================
  RVM has encountered a not yet trusted .rvmrc file in the
  current working directory which contains the following code:
  ============================================================

rvm ruby-1.8.7@rails2

  ============================================================
  Trusting an .rvmrc file means that whenever you cd into the
  directory RVM will excecute this .rvmrc script in your shell

  Do you wish to trust this .rvmrc from now on?
  ============================================================
  (y for yes, n for no) > 

2/build_log
__rvm_reset:14: no matches found: /Users/tsedano/.rvm/bin/default_*
__rvm_reset:14: no matches found: /Users/tsedano/.rvm/bin/passenger_*
__rvm_reset:14: no matches found: /Users/tsedano/.rvm/bin/editor_*
The Gemfile's dependencies are satisfied
rake aborted!
Error loading MorningGlory configuration files. Please check config/morning_glory.yml is configured correctly.
/Users/tsedano/.goldberg/projects/CMUEducation2/code/Rakefile:11
(See full trace by running task with --trace)
(in /Users/tsedano/.goldberg/projects/CMUEducation2/code)

3/build_log
__rvm_reset:14: no matches found: /Users/tsedano/.rvm/bin/default_*
__rvm_reset:14: no matches found: /Users/tsedano/.rvm/bin/passenger_*
__rvm_reset:14: no matches found: /Users/tsedano/.rvm/bin/editor_*
Gemset 'rails2tmp' does not exist, rvm gemset create 'rails2tmp' first.
zsh:1: command not found: bundle
zsh:1: command not found: bundle

6/build_log
__rvm_reset:14: no matches found: /Users/tsedano/.rvm/bin/default_*
__rvm_reset:14: no matches found: /Users/tsedano/.rvm/bin/passenger_*
__rvm_reset:14: no matches found: /Users/tsedano/.rvm/bin/editor_*
ESC[31mCould not find activesupport-2.3.4 in any of the sourcesESC[0m
ESC[31mCould not find activesupport-2.3.4 in any of the sourcesESC[0m

**Comment by aakashd** [comment]
We have done some major change in the way we are handling Gemfile.lock and also some environment changes. Please check if this solves the problem you are facing. If not we can probably discuss the issue over skype in greater details.

**Comment by professor** [comment]
I did a fresh project install and I'm no longer able to reproduce this issue, so I'm closing it.
