### ISSUE TITLE
generating rcov on specs

### ISSUE THREAD

**Issue by professor** [srushti/goldberg#39]
This is a feature request

I'd like to configure goldberg to use rcov on my specs. 

Running http://rubygems.org/gems/metrical or metrics_fu is a bonus.

**Comment by srushti** [comment]
I'm going to be working on getting a list of issues we want for our 1.0 release this weekend. As far as the rcov report is concerned, I think we would allow you to create a task which does that and dumps the reports to a specific folder which goldberg will pick up display through the web interface.

**Comment by kaiwren** [comment]
@srushti Do you want to add a story for publishing build artefacts, then? I did a search through the tickets and nothing came up.

**Comment by srushti** [comment]
#41 is the issue that covers this.
