### ISSUE TITLE
missing image /images/not_available.png

### ISSUE THREAD

**Issue by professor** [srushti/goldberg#43]
If you add a new project and goldberg starts a build, we get a missing image warning on the main page.

ActionController::RoutingError (No route matches "/images/not_available.png"):

The code that generates the request is here:

  def project_status_image(status)
    image_tag (status == 'building' ? "#{status}.gif" : "#{status}.png"), :alt => status, :title => status
  end     

I have a screenshot if its helpful.

(There's a side issue on why I'm getting this status at all. That may be worth discussing.)

**Comment by srushti** [comment]
I haven't figured out a good icon to use for when no build has happened yet. Do you have any suggestions?
Also, the not_available thing should only until the poller picks up the project for its first build. Are you saying it stays this way for longer?

**Comment by professor** [comment]
Right now, the poller isn't starting up for me automatically when I start the server. So I need to do the following.....
bin/goldberg start
bin/goldberg start_poller

I'm presently in a situation where I've done the first command, but haven't done the second one yet.

**Comment by srushti** [comment]
I just tried the same on my machine & it seems to work fine. The poller starts if I just run "bin/goldberg start".

**Comment by professor** [comment]
On both my macbook pro (10.6) and my mac mini (10.5), the poller doesn't start. (I'm assuming it doesn't start since I get the missing image bug.) How should I go about debugging the problem.
