### ISSUE TITLE
A versioned Gemfile.lock shouldn't get deleted

### ISSUE THREAD

**Issue by srushti** [srushti/goldberg#60]
Goldberg seems to be deleting the Gemfile.lock even if it is versioned. https://gist.github.com/fa4eb6cc16d0ced1c0c2

**Comment by aakashd** [comment]
I think Rohit's pull request will resolve the issue. Have you checked the pull request?

**Comment by srushti** [comment]
Fixed in 27a112093e3cdf9e63ed015bba994da88dcda90f (from @rohit) & 338782cfa0c089a488a8b840a672204f603e1899.
