### ISSUE TITLE
bundle install fails

### ISSUE THREAD

**Issue by rnjn** [srushti/goldberg#68]
I checked the source out, did a bundle install. This failed.

gogo@rnjn  ~goldberg(master) >bundle install
Fetching source index for http://rubygems.org/
Using rake (0.9.0) 
Using abstract (1.0.0) 
Using activesupport (3.0.6) 
Using builder (2.1.2) 
Using i18n (0.5.0) 
Using activemodel (3.0.6) 
Using erubis (2.6.6) 
Using rack (1.2.3) 
Using rack-mount (0.6.14) 
Using rack-test (0.5.7) 
Using tzinfo (0.3.27) 
Using actionpack (3.0.6) 
Using mime-types (1.16) 
Using polyglot (0.3.1) 
Using treetop (1.4.9) 
Using mail (2.2.19) 
Using actionmailer (3.0.6) 
System.java:-2:in `arraycopy': java.lang.ArrayIndexOutOfBoundsException
    from DefaultResolver.java:111:in`makeTime'
    from DefaultResolver.java:277:in `create'
    from DefaultResolver.java:317:in`handleScalar'

**Comment by rnjn** [comment]
failed with jruby-1.6.0 only. worked alright with ruby-1.9.2-p180. maybe has something to do with my env.

**Comment by srushti** [comment]
No it's not just your env. I've noticed it fail on jruby, and when I googled for it I saw people reporting the same arraycopy problem with jruby for other projects.

**Comment by ganeshkumar** [comment]
@rnjn, Install jruby-1.6.2. This solves the problem

**Comment by rnjn** [comment]
it does, thanks @ganeshkumar. closing this.

and i thought things just worked :p
