### ISSUE TITLE
Using project-specific goldberg_config.rb causes build to silently fail (no output)

### ISSUE THREAD

**Issue by localshred** [srushti/goldberg#74]
I have tried various incantations of the goldberg_config.rb file, but in every case, when I specify any commands to override (such as `ruby=` or `environment_variables=` or even `command=`), the build will fail without producing any output. However, if I leave the file in place and remove any assignments from the configure block, I get normal build output.

Here are a few sample configs I tried that produced no output on failed builds:

``` ruby
Project.configure do |c|
  c.ruby = '1.9.2-p0'
  c.environment_variables = {'RACK_ENV' => 'test', 'CHARSET' => 'latin1'}
  c.rake_task = 'ci'
end
Project.configure do |c|
  c.ruby = '1.9.2-p0'
  c.environment_variables = {'RACK_ENV' => 'test', 'CHARSET' => 'latin1'}
  c.command = 'bundle exec rake ci'
end
Project.configure do |c|
  c.ruby = '1.9.2-p0'
  c.command = 'bundle exec rake ci'
end
Project.configure do |c|
  c.command = 'bundle exec rake ci'
end
```

If the file is empty or non-existant, the build produces output normally. Also of note, the poller log produces only a single line of output on failed builds: "Build Failed". No warnings or stack traces are output.

**Comment by daveworth** [comment]
I'm not sure this should be labeled as a feature.  I'm running into the same scenario.  I have two Goldberg hosts (migrating from one to another). The old one displays output, the latter does not, using the same goldberg_config.rb's in the various projects.  The emails and other hooks produce correct outputs.

**Comment by srushti** [comment]
@daveworth Oops! That certainly wasn't a feature. That was a mistake in tagging, and subsequently made me not look at it.

@localshred This should long since have been fixed though. I'm going to close it. Please, let me know if you're facing issues (this or other).
