### ISSUE TITLE
bin/goldberg add not adding project

### ISSUE THREAD

**Issue by nicholasf** [srushti/goldberg#76]
Hi,

When trying to add a github project to Goldberg:

```
[deploy@li269-181 goldberg]$ bin/goldberg add git@github.com:tfw/ADA-CMS.git ada-cms          
executing /usr/bin/env bash -c "git clone --depth 1 git@github.com:tfw/ADA-CMS.git /home/deploy/.goldberg/projects/ada-cms/code --branch master"
error: unknown option `branch'
usage: git-clone [options] [--] <repo> [<dir>]

    -n, --no-checkout     don't create a checkout
    --bare                create a bare repository
    --naked               create a bare repository
    -l, --local           to clone from a local repository
    --no-hardlinks        don't use local hardlinks, always copy
    -s, --shared          setup as a shared repository
    --template ...        path to the template directory
    -q, --quiet           be quiet
    --reference ...       reference repository
    -o, --origin ...      use <name> instead of 'origin' to track upstream
    -u, --upload-pack ...
                          path to git-upload-pack on the remote
    --depth ...           create a shallow clone of that depth
    --use-separate-remote
                          compatibility, do not use
    --no-separate-remote  compatibility, do not use

ada-cms successfully added.
[deploy@li269-181 goldberg]$ bin/goldberg list
  Project Load (0.8ms)  SELECT "projects".* FROM "projects"
```

So, the project isn't added successfully - the branch arg isn't recognised - but the response message is that it's successful. 

Adding with the -b arg results in the same.

```
[deploy@li269-181 goldberg]$ bin/goldberg add git@github.com:tfw/ADA-CMS.git ada-cms -b master
executing /usr/bin/env bash -c "git clone --depth 1 git@github.com:tfw/ADA-CMS.git /home/deploy/.goldberg/projects/ada-cms/code --branch master"
error: unknown option `branch'
```

**Comment by srushti** [comment]
The wrong message being displayed has been fixed with 312de9abc06d32a8089e48bab2826d69d843b797.
As far as the argument not being recognised, could you tell me the version of git you're using? Basically, I want the output of the `git --version` command. It looks like whatever you are using doesn't support specifying the branch. With that information I'll probably suggest you to upgrade your git, but I would like to know the version of git anyway.

**Comment by nicholasf** [comment]
[deploy@li269-181 ~]$ git --version
git version 1.5.5.6

**Comment by srushti** [comment]
Thanks for the response. I'd say you ought to upgrade git. My version is `1.7.5.2` (through homebrew), and the current version on ubuntu is `1.7.1`. I'm not sure when the `--branch` option was added to git, but we certainly won't be trying to be compatible with `1.5`.
I'm going to close this issue. Please reopen it if you the problem persists in the later version, or if it is impossible for you to upgrade. If the latter is true we'll take a closer look to see what it would involve, but I can't promise anything.

**Comment by nicholasf** [comment]
No worries.

It might be worth updating your docs to specify the oldest version of git you do support (if the information is not already there).

**Comment by srushti** [comment]
Yeah, I was thinking the same thing. The information isn't already there, and we're hunting through the documentation of older versions of git-clone to see when the `--branch` might have been added.

**Comment by srushti** [comment]
The documentation has been updated. The minimum version of git you can use 1.6.5.
