### ISSUE TITLE
git submodule support

### ISSUE THREAD

**Issue by lucasefe** [srushti/goldberg#78]
Hi, is there any way to tell goldberg to do a `git submodule init and git submodule update` before running the build process? 

Cheers
Lucas

**Comment by achamian** [comment]
Currently Goldberg doesn't support git submodules out of the box, as not many projects have submodules. But you can easily achieve it by writing a custom rake command.

**Comment by srushti** [comment]
I think goldberg can do this quite easily. All we'll need to do is to look for a .gitmodules file and accordingly run init and update.

**Comment by srushti** [comment]
@suryagaddipati submitted a trivial fix for this with #82.
