### ISSUE TITLE
Build log should display select Ruby interpreter.

### ISSUE THREAD

**Issue by lucasefe** [srushti/goldberg#80]
It would be useful to see the selected ruby interpreter when building a project. It's not really that evident what's going on, so the log could include more information regarding environment. 

Something like: 

"Defaulting to system ruby"

or 

"Using RVM's ruby 1.9.2-p180"

Thanks

Lucas Florio

**Comment by srushti** [comment]
We already mention it in a couple of places, but I suppose we could make it a lot clearer. The first line in the log will be the message from RVM, e.g. "Using /home/goldberg/.rvm/gems/ruby-1.9.2-p180 with gemset goldberg-goldberg". Also, the title of the project page itself mentions the RUBY_VERSION (but, unfortunately not the patch level or any other information). We'll see if we can clear this up any.

**Comment by lucasefe** [comment]
Ok, good enough for me :)
