### ISSUE TITLE
Clicking 'Force Build' gives no feedback to the user

### ISSUE THREAD

**Issue by kaiwren** [srushti/goldberg#85]
Clicking force build currently has no immediate visible effect. 

Only when the build actually starts _and_ the page self updates (which even with a single build can often take > 10s) does any visible change occur.

There should be an additional build state of 'queued' to handle this situation.

**Comment by srushti** [comment]
Added a little bit of text to the force build button if a build is currently queued 83f4cf7b51906a1603e2ca6f36750bdd99641b9b.
