### ISSUE TITLE
config.timeout not working correctly

### ISSUE THREAD

**Issue by kaiwren** [srushti/goldberg#96]
http://goldberg.c42.in/projects/rspec_core_jruby has its timeout set to 3.hours but is definitely being killed a lot sooner

**Comment by kaiwren** [comment]
This is likely an issue with our server setup and not Goldberg itself. Will need @achamian's help to see what's going on.

**Comment by srushti** [comment]
Did you ever figure this out? Is it in fact a goldberg issue?

**Comment by srushti** [comment]
I'm closing this since it looks like timeout is working fine now. Let me know if you face issues again.
