### ISSUE TITLE
Build gets marked as "cancelled" before it finishes?

### ISSUE THREAD

**Issue by levity** [srushti/goldberg#99]
For some reason my builds are getting marked as cancelled, even before they finish, even while the build log continues to update. Is there a time limit or something built into Goldberg by default?

**Comment by kaiwren** [comment]
Does your build take longer than 10 minutes? 

The default timeout is 10 minutes, though we should probably call that out clearly on the readme. Take a look at the Project config section of the README to change the timeout.

If this doesn't fix your problem, then you're probably seeing the same thing as #96.

**Comment by levity** [comment]
That would explain it. Yes, I'm running a large monolithic spec with lots of acceptance tests on a slow machine. Usually takes about 20 minutes. Thanks for delivering the RTFM gently. :)

**Comment by kaiwren** [comment]
Not at all - I ran into the same issue when setting up a build a few days ago. I just updated the README to call this out.
